./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwBecerra BecerraRivero.pgn > BecerraRivero.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbBecerra BecerraRivero.pgn > BecerraRivero.asblack.pgn

./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbDe DeLaBourdonnais.pgn > DeLaBourdonnais.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwDe DeLaBourdonnais.pgn > DeLaBourdonnais.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbPerez DominguezPerez.pgn > DominguezPerez.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwPerez DominguezPerez.pgn > DominguezPerez.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbGranda GrandaZuniga.pgn > GrandaZuniga.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwGranda GrandaZuniga.pgn > GrandaZuniga.aswhite.pgn

./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbGur GurevichD.pgn > GurevichD.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwGur GurevichD.pgn > GurevichD.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbGur GurevichM.pgn > GurevichM.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwGur GurevichM.pgn > GurevichM.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbIll IllescasCordoba.pgn > IllescasCordoba.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwIll IllescasCordoba.pgn > IllescasCordoba.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbIva IvanovA.pgn > IvanovA.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwIva IvanovA.pgn > IvanovA.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbIva IvanovI.pgn > IvanovI.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwIva IvanovI.pgn > IvanovI.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbJan Janowski.pgn > Janowski.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwJan Janowski.pgn > Janowski.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbMac MacKenzie.pgn > MacKenzie.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwMac MacKenzie.pgn > MacKenzie.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbPol PolgarJ.pgn > PolgarJ.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwPol PolgarJ.pgn > PolgarJ.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbPol PolgarS.pgn > PolgarS.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwPol PolgarS.pgn > PolgarS.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbPol PolgarZ.pgn > PolgarZ.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwPol PolgarZ.pgn > PolgarZ.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbSul SultanKhan.pgn > SultanKhan.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwSul SultanKhan.pgn > SultanKhan.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbTor TorreRepetto.pgn > TorreRepetto.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwTor TorreRepetto.pgn > TorreRepetto.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbVac VachierLagrave.pgn > VachierLagrave.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwVac VachierLagrave.pgn > VachierLagrave.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbVal VallejoPons.pgn > VallejoPons.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwVal VallejoPons.pgn > VallejoPons.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbWely VanWely.pgn > VanWely.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwWely VanWely.pgn > VanWely.aswhite.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TbWang WangH.pgn > WangH.asblack.pgn
./pgn-extract/pgn-extract -Wxlalg -C -N -V -D -s -TwWang WangH.pgn > WangH.aswhite.pgn
